config/routes.rb
SearchMailboxes::Application.routes.draw do
  get 'emails'              => 'search#emails',  as: :emails_search
  get 'emails/:id'          => 'search#show', as: :email
  get 'emails/download/:id' => 'search#download', as: :email_download

  root 'search#emails'

  

end

app/models/email.rb
class Email < ActiveRecord::Base
  validates_uniqueness_of :file_name, allow_nil: true

  searchable do
    text :to, :from, :subject
    string :file_name
    text :body do
      body[0..10_000]
    end
    time :received
  end

  def full_body
    header + "\n\n" + body
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def emails
    @search = search_solr
    if params[:download] && @search.total > 0
      generate_zip do |zipname, zip_path|
        send_file zip_path, :type => 'application/zip', :disposition => 'attachment', :filename => zipname
      end
    else
      @emails = @search.try(:results) || []
    end
  end


  def show
    @email = Email.find(params[:id])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def download
    @email = Email.find(params[:id])
    send_data @email.full_body,
              filename: @email.file_name,
              type: 'application/octet-stream'
  end

  private

  def search_solr
    if params[:query].present?
      Email.search do
        if params[:query] =~ /\.(emlx|txt)$/
           with :file_name, params[:query]
        else
           fulltext params[:query] do
             fields *params[:fields] if params[:fields]
           end
        end
        with(:received).greater_than(params[:date_from]) if params[:date_from].present?
        with(:received).less_than(params[:date_to]) if params[:date_to].present?
        paginate :page => params[:page] || 1, per_page: params[:per_page] || 20
        order_by :received, :asc
      end
    else
      nil
    end
  end

  def generate_zip(&block)
    export_file_name = 'emails-export.zip'
    page = 0
    params[:per_page] = 100
    temp_dir = Dir.mktmpdir
    zip_path = File.join(temp_dir, export_file_name)
    Rails.logger.info("zip file location is #{zip_path}")

    require 'zip/file'

    ::Zip::ZipFile::open(zip_path, true) do |zipfile|
      begin
        page += 1
        params[:page] = page
        search = search_solr
        search.results.each do |email|
          Rails.logger.info("adding file #{email.file_name}")
          zipfile.get_output_stream(email.file_name) do |io|
            io.write email.full_body
          end
        end
      end while page < search.results.total_pages
    end
    block.call export_file_name, zip_path
  ensure
    #FileUtils.rm_rf temp_dir if temp_dir rescue nil
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : 'Email Search'
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
    = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js'
    = stylesheet_link_tag 'application', :media => 'all'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Start New Search
          .container.nav-collapse
            %ul.nav
              -#%li= link_to "Link 1", "/path1"
              -#%li= link_to "Link 2", "/path2"
              -#%li= link_to "Link 3", "/path3"

    .container-fluid
      = bootstrap_flash
      = yield
    
      %footer
        %p &copy; 2018
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag 'application'

app/views/search/_email.html.haml
%h2
  = email.file_name
%h4
  = link_to "download", email_download_path(email)
  |
  = link_to "permalink", email_path(email), onclick: "window.open(this.href, '#{email.file_name}', 'height=1200, width=800');return false;" 
.email-contents
  %table#email-contents.table.table-bordered
    %thead
    %tbody
      %tr
        %td
          Date:
          = email.received
      %tr
        %td
          From:
          = email.from
      %tr
        %td
          To:
          = email.to
      %tr
        %td
          Subject:
          = email.subject
  %pre.pre-scrollable.email-body
    = email.body

app/views/search/emails.html.haml
.row-fluid
  .span6
    .email-search
      %form#email-search-form(class="well form-search" action="#{emails_search_path}")
        .form-group
          =date_field_tag :date_from, params[:date_from], :as => :string, placeholder: 'MM/DD/YYYY From'
          =date_field_tag :date_to, params[:date_to], :as => :string, placeholder: 'MM/DD/YYYY To'
        =select_tag(:fields, options_for_select(%w(from to subject body), params[:fields]), { class: 'field-select', multiple: true, size: 4 })
        .form-group
          %input(type="text" autofocus="autofocus" name="query"  class="input-long search-query" placeholder="Matches..." value="#{params[:query]}")
          %p.small
            Use + or - to exclude or include a term, for example "pizza -meat"
        %div
          %input.btn.btn-large.btn-success(type="submit" id="search" value="search")
          %input.btn.btn-large.btn-warning(type="submit" id="download" name="download" value="download")

      %p
        - if @search
          = @search.results.total_count
        - else
          0
        documents matched out of
        = Email.count
        documents total.
      %p
        = paginate @search.results if @search

      %table#email-results.table.table-condensed.table-hover.table-bordered
        %thead
          %tr
            %th File
            %th Sent
            %th From/To
            %th Subject
        %tbody
          - @emails.each do |email|
            %tr(class="email-summary" data-email-id="#{email.id}")
              %td
                = link_to email.file_name, email_download_path(email)
              %td.nowrap
                = email.received.in_time_zone('Pacific Time (US & Canada)').to_date.to_s if email.received.present?
              %td
                From:
                = email.from
                %br
                To:
                = email.to
              %td
                = email.subject

      %p
        = paginate @search.results if @search

  .span6
    #email-content

app/views/search/show.html.haml
= render partial: "email", locals: { email: @email }

app/views/search/show.js.erb
$('#email-content').html("<%= escape_javascript render(partial: "email", locals: { email: @email} ) %>");